



ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ACCOUNT_DEACTIVATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ROLE_CHANGED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PURCHASE_ORDER_SENT';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INVOICE_OVERDUE';
