import {
  Activity,
  ArrowLeftRight,
  BadgeCheck,
  BarChart,
  Bell,
  BookAIcon,
  BookCheckIcon,
  BookUser,
  Building2,
  ChartNoAxesCombined,
  CircleDollarSign,
  ClipboardCheck,
  ClipboardList,
  Component,
  CreditCard,
  Factory,
  FileCheck2,
  FileText,
  GitBranch,
  Layers,
  ListChecks,
  Mail,
  MessageCircle,
  Package,
  PackageSearch,
  ReceiptText,
  Recycle,
  ScanBarcode,
  Settings,
  Share2,
  ShoppingCart,
  SlidersHorizontal,
  TriangleAlert,
  Truck,
  UserCheck,
  UserLock,
  Wallet,
  Warehouse,
  type IconComponent,
} from "@repo/ui/icons";

/**
 * Destinations offered by the command palette, kept in sidebar order so the
 * palette reads like the navigation it shadows. `section` is the sidebar
 * sub-menu an entry sits under and is shown next to the label.
 */
export interface NavigationCommand {
  id: string;
  label: string;
  href: string;
  group: string;
  section?: string;
  icon: IconComponent;
  keywords?: string[];
  external?: boolean;
  adminOnly?: boolean;
}

const MARKETING = "Marketing & Sales";
const SUPPLY_CHAIN = "Operations & Supply Chain";
const FINANCE = "Finance";
const ADMINISTRATION = "Administration";

export const NAVIGATION_COMMANDS: NavigationCommand[] = [
  {
    id: "nav:/",
    label: "Dashboard",
    href: "/",
    group: "Overview",
    icon: ChartNoAxesCombined,
    keywords: ["home", "overview", "metrics"],
  },

  {
    id: "nav:landing-page-builder",
    label: "Landing Page Builder",
    href: "https://app.landingi.com/landings",
    group: MARKETING,
    section: "Landing Page",
    icon: FileText,
    external: true,
    keywords: ["landingi", "builder", "pages"],
  },
  {
    id: "nav:/landing-page-trackers",
    label: "Landing Page Trackers",
    href: "/landing-page-trackers",
    group: MARKETING,
    section: "Landing Page",
    icon: Layers,
    keywords: ["tracking", "utm", "conversions"],
  },
  {
    id: "nav:/leads/lead-master",
    label: "Lead Master",
    href: "/leads/lead-master",
    group: MARKETING,
    section: "Lead Management",
    icon: ListChecks,
    keywords: ["leads", "enquiries", "prospects"],
  },
  {
    id: "nav:/leads/unassigned-leads",
    label: "Unassigned Leads",
    href: "/leads/unassigned-leads",
    group: MARKETING,
    section: "Lead Management",
    icon: Share2,
    keywords: ["queue", "allocation"],
  },
  {
    id: "nav:/leads/assigned",
    label: "Assigned Leads",
    href: "/leads/assigned",
    group: MARKETING,
    section: "Lead Management",
    icon: UserCheck,
    keywords: ["owner", "allocation"],
  },
  {
    id: "nav:/leads/accounts",
    label: "Accounts",
    href: "/leads/accounts",
    group: MARKETING,
    section: "Lead Management",
    icon: Building2,
    keywords: ["companies", "customers", "crm"],
  },
  {
    id: "nav:/leads/contacts",
    label: "Contacts",
    href: "/leads/contacts",
    group: MARKETING,
    section: "Lead Management",
    icon: BookUser,
    keywords: ["people", "crm"],
  },
  {
    id: "nav:/campaigns/segments",
    label: "Segments",
    href: "/campaigns/segments",
    group: MARKETING,
    section: "Campaign Management",
    icon: ListChecks,
    keywords: ["audience", "lists", "targeting"],
  },
  {
    id: "nav:/campaigns/email",
    label: "Email Campaigns",
    href: "/campaigns/email",
    group: MARKETING,
    section: "Campaign Management",
    icon: Mail,
    keywords: ["broadcast", "newsletter", "resend"],
  },
  {
    id: "nav:/campaigns/whatsapp",
    label: "WhatsApp Campaigns",
    href: "/campaigns/whatsapp",
    group: MARKETING,
    section: "Campaign Management",
    icon: MessageCircle,
    keywords: ["wa", "messaging", "broadcast"],
  },
  {
    id: "nav:/sales/products",
    label: "Product Configuration",
    href: "/sales/products",
    group: MARKETING,
    section: "Sales Management",
    icon: Package,
    keywords: ["catalogue", "catalog", "sku", "items"],
  },
  {
    id: "nav:/sales/price-books",
    label: "Price Books",
    href: "/sales/price-books",
    group: MARKETING,
    section: "Sales Management",
    icon: BookCheckIcon,
    keywords: ["pricing", "rate card", "discounts"],
  },
  {
    id: "nav:/sales/opportunities",
    label: "Opportunities",
    href: "/sales/opportunities",
    group: MARKETING,
    section: "Sales Management",
    icon: BookAIcon,
    keywords: ["deals", "pipeline", "forecast"],
  },
  {
    id: "nav:/sales/quotes",
    label: "Quotes",
    href: "/sales/quotes",
    group: MARKETING,
    section: "Sales Management",
    icon: ReceiptText,
    keywords: ["quotation", "proposal", "pricing"],
  },
  {
    id: "nav:/sales/orders",
    label: "Orders",
    href: "/sales/orders",
    group: MARKETING,
    section: "Sales Management",
    icon: ShoppingCart,
    keywords: ["sales orders", "so", "bookings"],
  },
  {
    id: "nav:/sales/approvals",
    label: "Approvals",
    href: "/sales/approvals",
    group: MARKETING,
    section: "Sales Management",
    icon: ClipboardCheck,
    keywords: ["sign off", "discount approval", "pending"],
  },

  {
    id: "nav:/warehouse",
    label: "Warehouses & Bins",
    href: "/warehouse",
    group: SUPPLY_CHAIN,
    section: "Warehouse",
    icon: Warehouse,
    keywords: ["locations", "storage", "racks"],
  },
  {
    id: "nav:/warehouse/putaway",
    label: "Putaway Queue",
    href: "/warehouse/putaway",
    group: SUPPLY_CHAIN,
    section: "Warehouse",
    icon: Package,
    keywords: ["inbound", "stocking"],
  },
  {
    id: "nav:/warehouse/pick-lists",
    label: "Pick Lists",
    href: "/warehouse/pick-lists",
    group: SUPPLY_CHAIN,
    section: "Warehouse",
    icon: ListChecks,
    keywords: ["picking", "fulfilment", "fulfillment"],
  },
  {
    id: "nav:/warehouse/packages",
    label: "Packages",
    href: "/warehouse/packages",
    group: SUPPLY_CHAIN,
    section: "Warehouse",
    icon: Truck,
    keywords: ["shipping", "dispatch", "packing"],
  },
  {
    id: "nav:/materials",
    label: "Material Master",
    href: "/materials",
    group: SUPPLY_CHAIN,
    section: "Materials",
    icon: Layers,
    keywords: ["items", "sku", "raw materials"],
  },
  {
    id: "nav:/materials/availability",
    label: "Build Availability",
    href: "/materials/availability",
    group: SUPPLY_CHAIN,
    section: "Materials",
    icon: ListChecks,
    keywords: ["can build", "coverage"],
  },
  {
    id: "nav:/materials/shortages",
    label: "Shortages",
    href: "/materials/shortages",
    group: SUPPLY_CHAIN,
    section: "Materials",
    icon: TriangleAlert,
    keywords: ["short", "gaps", "deficit"],
  },
  {
    id: "nav:/materials/requisitions",
    label: "Material Requisitions",
    href: "/materials/requisitions",
    group: SUPPLY_CHAIN,
    section: "Materials",
    icon: ClipboardList,
    keywords: ["issue", "demand", "mr"],
  },
  {
    id: "nav:/materials/consumption",
    label: "Consumption & Wastage",
    href: "/materials/consumption",
    group: SUPPLY_CHAIN,
    section: "Materials",
    icon: Recycle,
    keywords: ["scrap", "usage", "yield"],
  },
  {
    id: "nav:/purchasing",
    label: "Purchasing Overview",
    href: "/purchasing",
    group: SUPPLY_CHAIN,
    section: "Purchasing",
    icon: BarChart,
    keywords: ["procurement", "spend"],
  },
  {
    id: "nav:/purchasing/suppliers",
    label: "Suppliers",
    href: "/purchasing/suppliers",
    group: SUPPLY_CHAIN,
    section: "Purchasing",
    icon: Building2,
    keywords: ["vendors", "procurement"],
  },
  {
    id: "nav:/purchasing/requisitions",
    label: "Purchase Requisitions",
    href: "/purchasing/requisitions",
    group: SUPPLY_CHAIN,
    section: "Purchasing",
    icon: ClipboardList,
    keywords: ["pr", "indent", "request"],
  },
  {
    id: "nav:/purchasing/orders",
    label: "Purchase Orders",
    href: "/purchasing/orders",
    group: SUPPLY_CHAIN,
    section: "Purchasing",
    icon: ShoppingCart,
    keywords: ["po", "procurement"],
  },
  {
    id: "nav:/purchasing/goods-receipts",
    label: "Goods Receipts",
    href: "/purchasing/goods-receipts",
    group: SUPPLY_CHAIN,
    section: "Purchasing",
    icon: FileCheck2,
    keywords: ["grn", "inbound", "receiving"],
  },
  {
    id: "nav:/purchasing/quality",
    label: "Quality Checks",
    href: "/purchasing/quality",
    group: SUPPLY_CHAIN,
    section: "Purchasing",
    icon: BadgeCheck,
    keywords: ["qc", "inspection", "rejection"],
  },
  {
    id: "nav:/inventory",
    label: "Inventory Overview",
    href: "/inventory",
    group: SUPPLY_CHAIN,
    section: "Inventory",
    icon: BarChart,
    keywords: ["stock summary"],
  },
  {
    id: "nav:/inventory/stock",
    label: "Stock Positions",
    href: "/inventory/stock",
    group: SUPPLY_CHAIN,
    section: "Inventory",
    icon: PackageSearch,
    keywords: ["on hand", "balance", "quantity"],
  },
  {
    id: "nav:/inventory/movements",
    label: "Stock Ledger",
    href: "/inventory/movements",
    group: SUPPLY_CHAIN,
    section: "Inventory",
    icon: ArrowLeftRight,
    keywords: ["movements", "transactions", "history"],
  },
  {
    id: "nav:/inventory/counts",
    label: "Stock Counts",
    href: "/inventory/counts",
    group: SUPPLY_CHAIN,
    section: "Inventory",
    icon: ScanBarcode,
    keywords: ["cycle count", "audit", "physical"],
  },
  {
    id: "nav:/inventory/reorder-rules",
    label: "Reorder Policies",
    href: "/inventory/reorder-rules",
    group: SUPPLY_CHAIN,
    section: "Inventory",
    icon: SlidersHorizontal,
    keywords: ["min max", "safety stock", "rules"],
  },
  {
    id: "nav:/inventory/alerts",
    label: "Inventory Alerts",
    href: "/inventory/alerts",
    group: SUPPLY_CHAIN,
    section: "Inventory",
    icon: TriangleAlert,
    keywords: ["warnings", "low stock"],
  },
  {
    id: "nav:/inventory/valuation",
    label: "Valuation",
    href: "/inventory/valuation",
    group: SUPPLY_CHAIN,
    section: "Inventory",
    icon: Wallet,
    keywords: ["value", "costing", "worth"],
  },
  {
    id: "nav:/bom",
    label: "Bills of Materials",
    href: "/bom",
    group: SUPPLY_CHAIN,
    section: "BOM & Production",
    icon: GitBranch,
    keywords: ["bom", "recipe", "structure"],
  },
  {
    id: "nav:/production",
    label: "Production Orders",
    href: "/production",
    group: SUPPLY_CHAIN,
    section: "BOM & Production",
    icon: Factory,
    keywords: ["manufacturing", "work orders", "jobs"],
  },
  {
    id: "nav:/planning",
    label: "Production Board",
    href: "/planning",
    group: SUPPLY_CHAIN,
    section: "Planning",
    icon: ClipboardList,
    keywords: ["schedule", "board", "plan"],
  },
  {
    id: "nav:/planning/capacity",
    label: "Capacity",
    href: "/planning/capacity",
    group: SUPPLY_CHAIN,
    section: "Planning",
    icon: Activity,
    keywords: ["load", "utilisation", "utilization"],
  },
  {
    id: "nav:/planning/work-centers",
    label: "Work Centres",
    href: "/planning/work-centers",
    group: SUPPLY_CHAIN,
    section: "Planning",
    icon: Component,
    keywords: ["work centers", "machines", "lines"],
  },

  {
    id: "nav:/finance",
    label: "Finance Overview",
    href: "/finance",
    group: FINANCE,
    section: "Finance",
    icon: BarChart,
    keywords: ["accounting", "summary"],
  },
  {
    id: "nav:/finance/payables",
    label: "Accounts Payable",
    href: "/finance/payables",
    group: FINANCE,
    section: "Finance",
    icon: ReceiptText,
    keywords: ["ap", "supplier invoices", "bills"],
  },
  {
    id: "nav:/finance/receivables",
    label: "Accounts Receivable",
    href: "/finance/receivables",
    group: FINANCE,
    section: "Finance",
    icon: CircleDollarSign,
    keywords: ["ar", "customer invoices", "collections"],
  },
  {
    id: "nav:/finance/payments",
    label: "Payments",
    href: "/finance/payments",
    group: FINANCE,
    section: "Finance",
    icon: CreditCard,
    keywords: ["receipts", "settlements", "cash"],
  },

  {
    id: "nav:/admin/user-management",
    label: "User Management",
    href: "/admin/user-management",
    group: ADMINISTRATION,
    icon: UserLock,
    adminOnly: true,
    keywords: ["users", "roles", "permissions", "access"],
  },
  {
    id: "nav:/admin/notifications",
    label: "Notifications",
    href: "/admin/notifications",
    group: ADMINISTRATION,
    icon: Bell,
    keywords: ["alerts", "reminders"],
  },
  {
    id: "nav:/settings",
    label: "Settings",
    href: "/settings",
    group: ADMINISTRATION,
    icon: Settings,
    keywords: ["preferences", "configuration", "currency"],
  },
];
