import type { AdminUser, Approval } from "./approval-types";

export const DUMMY_ADMINS: AdminUser[] = [
  { id: "admin_1", name: "Admin One", email: "admin1@example.com" },
  { id: "admin_2", name: "Admin Two", email: "admin2@example.com" },
  { id: "admin_3", name: "Jane Admin", email: "jane@example.com" },
];

export const DEFAULT_APPROVALS: Approval[] = [
  {
    id: "apr_1",
    quoteNo: "QUO-2602-0001-A",
    targetObjectId: "quote:quo_1",
    targetRecordId: "quo_1",
    status: "PENDING",
    createdBy: "Sales Rep",
    createdById: "user_sales",
    createdDate: "2026-02-15T10:00:00.000Z",
    assigneeId: "admin_1",
    assigneeName: "Admin One",
    description: "Quote approval for Enterprise Software Deal",
  },
  {
    id: "apr_2",
    quoteNo: "QUO-2602-0002-A",
    targetObjectId: "quote:quo_2",
    targetRecordId: "quo_2",
    status: "APPROVED",
    createdBy: "Admin User",
    createdById: "user_admin",
    createdDate: "2026-02-14T09:00:00.000Z",
    completedDate: "2026-02-14T11:30:00.000Z",
    lastActorId: "admin_1",
    lastActorName: "Admin One",
    assigneeId: "admin_1",
    assigneeName: "Admin One",
    description: "Revised quote with support tier",
  },
  {
    id: "apr_3",
    quoteNo: "QUO-2602-0003-A",
    targetObjectId: "quote:quo_3",
    targetRecordId: "quo_3",
    status: "REJECTED",
    createdBy: "Sales Rep",
    createdById: "user_sales",
    createdDate: "2026-02-13T14:00:00.000Z",
    completedDate: "2026-02-13T16:00:00.000Z",
    lastActorId: "admin_2",
    lastActorName: "Admin Two",
    assigneeId: "admin_2",
    assigneeName: "Admin Two",
    description: "Annual renewal quote",
  },
  {
    id: "apr_4",
    quoteNo: "QUO-2602-0004-A",
    targetObjectId: "quote:quo_1",
    targetRecordId: "quo_1",
    status: "PENDING",
    createdBy: "Sales Rep",
    createdById: "user_sales",
    createdDate: "2026-02-16T08:00:00.000Z",
    assigneeId: "admin_1",
    assigneeName: "Admin One",
    description: "Additional quote revision for Acme Corp",
  },
  {
    id: "apr_5",
    quoteNo: "QUO-2602-0005-A",
    targetObjectId: "quote:quo_2",
    targetRecordId: "quo_2",
    status: "PENDING",
    createdBy: "Admin User",
    createdById: "user_admin",
    createdDate: "2026-02-16T09:15:00.000Z",
    assigneeId: "admin_2",
    assigneeName: "Admin Two",
    description: "Enterprise package quote for Globex",
  },
  {
    id: "apr_6",
    quoteNo: "QUO-2602-0006-A",
    targetObjectId: "quote:quo_3",
    targetRecordId: "quo_3",
    status: "PENDING",
    createdBy: "Sales Rep",
    createdById: "user_sales",
    createdDate: "2026-02-16T10:30:00.000Z",
    assigneeId: "admin_3",
    assigneeName: "Jane Admin",
    description: "Renewal quote extension request",
  },
  {
    id: "apr_7",
    quoteNo: "QUO-2602-0007-A",
    targetObjectId: "quote:quo_1",
    targetRecordId: "quo_1",
    status: "PENDING",
    createdBy: "Sales Rep",
    createdById: "user_sales",
    createdDate: "2026-02-16T11:00:00.000Z",
    assigneeId: "admin_1",
    assigneeName: "Admin One",
    description: "Volume discount quote approval",
  },
];

export const CURRENT_USER_ID = "admin_1";
