





INSERT INTO "currencies" ("code", "name", "symbol", "country")
VALUES
  ('USD', 'US Dollar', '$', 'United States'),
  ('EUR', 'Euro', '€', 'European Union'),
  ('JPY', 'Japanese Yen', '¥', 'Japan'),
  ('GBP', 'British Pound', '£', 'United Kingdom'),
  ('AUD', 'Australian Dollar', '$', 'Australia'),
  ('CAD', 'Canadian Dollar', '$', 'Canada'),
  ('CHF', 'Swiss Franc', 'CHF', 'Switzerland'),
  ('CNY', 'Chinese Yuan', '¥', 'China'),
  ('INR', 'Indian Rupee', '₹', 'India'),
  ('NZD', 'New Zealand Dollar', '$', 'New Zealand'),
  ('SGD', 'Singapore Dollar', '$', 'Singapore'),
  ('HKD', 'Hong Kong Dollar', '$', 'Hong Kong'),
  ('SEK', 'Swedish Krona', 'kr', 'Sweden'),
  ('NOK', 'Norwegian Krone', 'kr', 'Norway'),
  ('DKK', 'Danish Krone', 'kr', 'Denmark'),
  ('ISK', 'Icelandic Krona', 'kr', 'Iceland'),
  ('KRW', 'South Korean Won', '₩', 'South Korea'),
  ('TWD', 'New Taiwan Dollar', 'NT$', 'Taiwan'),
  ('MXN', 'Mexican Peso', '$', 'Mexico'),
  ('BRL', 'Brazilian Real', 'R$', 'Brazil'),
  ('ZAR', 'South African Rand', 'R', 'South Africa'),
  ('RUB', 'Russian Ruble', '₽', 'Russia'),
  ('TRY', 'Turkish Lira', '₺', 'Turkey'),
  ('PLN', 'Polish Zloty', 'zł', 'Poland'),
  ('CZK', 'Czech Koruna', 'Kč', 'Czechia'),
  ('HUF', 'Hungarian Forint', 'Ft', 'Hungary'),
  ('RON', 'Romanian Leu', 'lei', 'Romania'),
  ('BGN', 'Bulgarian Lev', 'лв', 'Bulgaria'),
  ('UAH', 'Ukrainian Hryvnia', '₴', 'Ukraine'),
  ('RSD', 'Serbian Dinar', 'дин', 'Serbia'),
  ('AED', 'UAE Dirham', 'د.إ', 'United Arab Emirates'),
  ('SAR', 'Saudi Riyal', '﷼', 'Saudi Arabia'),
  ('QAR', 'Qatari Riyal', '﷼', 'Qatar'),
  ('KWD', 'Kuwaiti Dinar', 'د.ك', 'Kuwait'),
  ('BHD', 'Bahraini Dinar', 'د.ب', 'Bahrain'),
  ('OMR', 'Omani Rial', '﷼', 'Oman'),
  ('ILS', 'Israeli New Shekel', '₪', 'Israel'),
  ('JOD', 'Jordanian Dinar', 'د.ا', 'Jordan'),
  ('LBP', 'Lebanese Pound', 'ل.ل', 'Lebanon'),
  ('IQD', 'Iraqi Dinar', 'ع.د', 'Iraq'),
  ('IRR', 'Iranian Rial', '﷼', 'Iran'),
  ('YER', 'Yemeni Rial', '﷼', 'Yemen'),
  ('THB', 'Thai Baht', '฿', 'Thailand'),
  ('MYR', 'Malaysian Ringgit', 'RM', 'Malaysia'),
  ('IDR', 'Indonesian Rupiah', 'Rp', 'Indonesia'),
  ('PHP', 'Philippine Peso', '₱', 'Philippines'),
  ('VND', 'Vietnamese Dong', '₫', 'Vietnam'),
  ('BND', 'Brunei Dollar', '$', 'Brunei'),
  ('KHR', 'Cambodian Riel', '៛', 'Cambodia'),
  ('LAK', 'Lao Kip', '₭', 'Laos'),
  ('MMK', 'Myanmar Kyat', 'K', 'Myanmar'),
  ('MNT', 'Mongolian Tugrik', '₮', 'Mongolia'),
  ('MOP', 'Macanese Pataca', 'MOP$', 'Macao'),
  ('FJD', 'Fijian Dollar', '$', 'Fiji'),
  ('PGK', 'Papua New Guinean Kina', 'K', 'Papua New Guinea'),
  ('PKR', 'Pakistani Rupee', '₨', 'Pakistan'),
  ('BDT', 'Bangladeshi Taka', '৳', 'Bangladesh'),
  ('LKR', 'Sri Lankan Rupee', '₨', 'Sri Lanka'),
  ('NPR', 'Nepalese Rupee', '₨', 'Nepal'),
  ('MVR', 'Maldivian Rufiyaa', 'Rf', 'Maldives'),
  ('AFN', 'Afghan Afghani', '؋', 'Afghanistan'),
  ('BTN', 'Bhutanese Ngultrum', 'Nu.', 'Bhutan'),
  ('KZT', 'Kazakhstani Tenge', '₸', 'Kazakhstan'),
  ('UZS', 'Uzbekistani Som', 'so''m', 'Uzbekistan'),
  ('AZN', 'Azerbaijani Manat', '₼', 'Azerbaijan'),
  ('GEL', 'Georgian Lari', '₾', 'Georgia'),
  ('AMD', 'Armenian Dram', '֏', 'Armenia'),
  ('EGP', 'Egyptian Pound', '£', 'Egypt'),
  ('NGN', 'Nigerian Naira', '₦', 'Nigeria'),
  ('KES', 'Kenyan Shilling', 'KSh', 'Kenya'),
  ('TZS', 'Tanzanian Shilling', 'TSh', 'Tanzania'),
  ('UGX', 'Ugandan Shilling', 'USh', 'Uganda'),
  ('GHS', 'Ghanaian Cedi', '₵', 'Ghana'),
  ('ETB', 'Ethiopian Birr', 'Br', 'Ethiopia'),
  ('MAD', 'Moroccan Dirham', 'د.م.', 'Morocco'),
  ('DZD', 'Algerian Dinar', 'د.ج', 'Algeria'),
  ('TND', 'Tunisian Dinar', 'د.ت', 'Tunisia'),
  ('MUR', 'Mauritian Rupee', '₨', 'Mauritius'),
  ('BWP', 'Botswana Pula', 'P', 'Botswana'),
  ('NAD', 'Namibian Dollar', '$', 'Namibia'),
  ('ZMW', 'Zambian Kwacha', 'ZK', 'Zambia'),
  ('MZN', 'Mozambican Metical', 'MT', 'Mozambique'),
  ('AOA', 'Angolan Kwanza', 'Kz', 'Angola'),
  ('XOF', 'West African CFA Franc', 'CFA', 'West African Union'),
  ('XAF', 'Central African CFA Franc', 'FCFA', 'Central African Union'),
  ('ARS', 'Argentine Peso', '$', 'Argentina'),
  ('CLP', 'Chilean Peso', '$', 'Chile'),
  ('COP', 'Colombian Peso', '$', 'Colombia'),
  ('PEN', 'Peruvian Sol', 'S/', 'Peru'),
  ('UYU', 'Uruguayan Peso', '$U', 'Uruguay'),
  ('BOB', 'Bolivian Boliviano', 'Bs.', 'Bolivia'),
  ('PYG', 'Paraguayan Guarani', '₲', 'Paraguay'),
  ('CRC', 'Costa Rican Colon', '₡', 'Costa Rica'),
  ('GTQ', 'Guatemalan Quetzal', 'Q', 'Guatemala'),
  ('DOP', 'Dominican Peso', 'RD$', 'Dominican Republic'),
  ('JMD', 'Jamaican Dollar', '$', 'Jamaica'),
  ('TTD', 'Trinidad and Tobago Dollar', '$', 'Trinidad and Tobago')
ON CONFLICT ("code") DO NOTHING;
